### ISSUE TITLE
View multi-sig and mint/burn transactions in Talib

### ISSUE THREAD

**Issue by tysloan** [liftedinit/roadmap#103]
Description: This story is to display multi-sig and mint/burn transactions in the UI of Talib. This is related to #96 which is adding these methods. These event types should be displayed in the Transactions list, Transaction details and tables. 

As a user, I want to view multi-sig and mint/burn transactions in Talib so that I am able to view all of my transaction activities.

- [x] Should display multi-sig transactions in Talib.
- [x] Should display mint/burn events in Talib.
- [x] Should be demoed.

**Comment by stanleyjones** [comment]
So... what exactly should we display for multi-sig transactions?

**Submit**

- What was submitted?
- By whom?

Problem: Transaction details don't currently include `from` which usually doesn't matter but in this case the `from` will be different from the submitted transaction's `from` so we should add it.

**Approve / Revoke**

- What was approved/revoked?
- By whom?

Problem 1: Right now we only get a token that refers back to the submitted transaction. We need to either A) allow submissions to be retrieved by token and let users navigate to the submission in the UI or B) embed the original submission in the approval/revocation.

Problem 2: Same as above. We need to include `from`.

**Create Account / Add Roles / Remove Roles**

I don't think these are a problem.

**Comment by stanleyjones** [comment]
cc @tysloan @hansl ^^^

**Comment by tysloan** [comment]
> cc @tysloan @hansl ^^^

I found the below examples of how etherscan handles different multisig method types:

Bancor: https://etherscan.io/address/0x5894110995b8c8401bd38262ba0c8ee41d4e4658 

Aragon: https://etherscan.io/address/0xcafe1a77e84698c83ca8931f54a755176ef75f2c

**Comment by hansl** [comment]
So etherscan does nothing special.

I'd like to see a timeline like this:

<img width="642" alt="image" src="https://user-images.githubusercontent.com/681969/230956895-7bd655b1-6e8d-4edc-bdc2-55c03a5025a8.png">

(this was whipped out in like 10 minutes, can be iterated, some fontawesome icons I couldn't make work).

We can have all the information to build a graph like this.

**Comment by stanleyjones** [comment]
Here's how they look right now...

**SUBMIT**

![Image](https://user-images.githubusercontent.com/405258/234374545-3692203f-cfb2-4eee-8d2f-46eec61efeda.png)

**APPROVE / REVOKE / WITHDRAW**

![Image](https://user-images.githubusercontent.com/405258/234374617-858344af-7006-4ec7-b77d-7ecff8205e9d.png)
