### ISSUE TITLE
Limit update/delete arbitrary data permissions to owner via a UI

### ISSUE THREAD

**Issue by tysloan** [liftedinit/roadmap#18]
Description: This story is associated with the work that has already been completed in [#2](https://github.com/liftedinit/roadmap/issues/2) and #16. The functionality of limiting permissions to the owner already exists. An error message should be presented to users that try to update/delete data that they are not the owner of.

Story ROI
Customer Need: Only data owners should be able to update or delete data on-chain. Users should be notified on screen when they are not able to update data.

Business Objective: Improved user experience.

**As a user, I want to protect my on-chain arbitrary data so that only I can modify it.**

- [x] Should be achievable via a UI (Gwen).
- [x] Should be able to limit the scope to the Manifest dev network.
- [x] Should be able to update or delete data as the owner that wrote it if has not previously been marked immutable.
- [x] Should present error message ("Only owners can edit this data.") when a user tries to update or delete data that they are not the owner of. 
- [x] Should be able to be demoed in the dev network.

[PRD](https://docs.google.com/document/d/1NyfRdqbguYu5n1GgFGlo5S9UPvOS7FEsCFdUy-A0S7Y/edit?usp=sharing)

Design: still needed.

---------------------
Tasks:

**Comment by stanleyjones** [comment]
I accidentally resolved this issue with https://github.com/liftedinit/gwen/pull/31.

**Comment by stanleyjones** [comment]
![Image](https://user-images.githubusercontent.com/405258/215222291-0bbe208f-98cd-444e-ab1f-0ac809cc4088.png)

This is the error provided by the back-end, but we can change it to be "Only owners can edit this data." if it's important.

**Comment by stanleyjones** [comment]
Live here: https://dev002_gwen.liftedinit.tech/#/settings/data

**Comment by stanleyjones** [comment]
Accepted as done via Slack.
