### ISSUE TITLE
View the current block height via a UI (Talib)

### ISSUE THREAD

**Issue by tysloan** [liftedinit/roadmap#28]
Description: This is the first end-to-end implementation of our block explorer, Talib. The block.info endpoint should be able to present the block height in the UI of Talib. QA is the target environment. 

Story ROI
Customer Need: A block explorer enables users to transparently view transactions and Network activity. Viewing block height is the first step to fully implemented blocked explorer for users but shows the network is live and real.

Business Objective: Talib provides core functionality to make transactions and the Manifest blockchain network externally visible. This project has been in the works for a long time and should be completed.

**As a user, I want to view the current block height of a network so that I stay informed.**

- [x] Should be achievable via a UI (Talib).
- [x]  Should be achievable via library (many-js).
- [x] Should be available from the network API (many-framework).
- [x] Should comply with the specification (many-protocol).
- [x] Should present the current block height from the block.info endpoint.
- [x] Should present an error message ("An error occurred.") to the user (in UI) if there is an error retrieving the data.
- [x] Should be deployed to QA environment.
- [x] Should be able to be demoed as an E2E implementation.

Open questions/considerations:
- What infrastructure will need to be stood up to support this? 
- How often is it updated?

Design:

![Image](https://user-images.githubusercontent.com/113936517/200690663-d4e7b70c-aa07-4de6-92c3-985d3a1e72c2.png)

![Image](https://user-images.githubusercontent.com/113936517/208753369-1ffa5c74-e338-4433-98e2-5f85d89499e3.png)

[PRD](https://docs.google.com/document/d/1YZYTwH3byq6e_ZdzDiEJD9CKgRPU1qRoqgbiQI-hGIA/edit?usp=sharing)

---------------------
Tasks:
[Fe] Design new Homepage : this require create a new page, add functionabilty to get from backend/network the information, 2 diferent api calls.
[BE] Modify the entity, model, service  and controller BlockInformation.
[TBD] we need to define if we are going to control the healt of the network in the backend and keep in the db the status changes or we are going to call from the FE directly and code some logic there to show errors and warnings.

Notes: 
Software Version will be get it from status.serverVersion (card #33  )
Protocol Version will be get it from status.protocolVersion ( card #32 )

Based on this response:
```
{
  status: {
    protocolVersion: 1,
    serverName: 'AbciModule(many-ledger)',
    publicKey: Map(6) {...},
    address: 'mahkmntgf27qb3xb4mm4evswbgpuyjgfwjxscdkh2uct4ypqbr',
    attributes: [ 0, 1, 2, 4, 5, 6, 8, [Array], 1002 ],
    serverVersion: '0.1.0',
    timeDeltaInSecs: 300
  }
} 
```

**Comment by mjsorribas** [comment]
@stanleyjones I've a question around our discussion about blockchain.info data, right now I need all this information to show in the frontend based on our current UI (we can split this  in a few  task to include it the next sprint)

Talib-backend use basically this fields to manage blockchain.info data

    • tsx_per_sec
    •  tsx_tps
    •  block_height
    •  hash_rate
    •  computer_power_used
    •  computer_power_available
    •  active_nodes
    •  total_nodes

I got this from blockchain.info

    • latestBlock:  BlockIdentifier {hash: ArrayBuffer; height: number;}
    • appHash: ArrayBuffer
    • retainedHeight: number

My questions are basically where I'll save it the info of the response:
1) block_height:   is equal  retainedHeight  or  latestBlock{height} ? 
2) hash_rate comes  inside appHash array or latestBlock{hash:array} ?
3) We are going to modify the current UI to adapt for the current information received or we area going to keep it and only fill it with this?

For next refinement
4)We are going to create a new call in many-js to get the other stuff or the idea is add more data to the blockchain.info?

**Comment by stanleyjones** [comment]
1. I think `block_height` is equal to `latestBlock.height`
2. I don't see anything resembling `hash_rate` in that response. @hansl ?
3. Yeah, we're going to have to change the UI to match the current API.
4. I was just talking with @tysloan about this earlier today. I think he'll schedule a call for us to discuss early next week. But basically the process will be something like: A) what does the UI need? B) can we get it from the current API? C) what changes do we propose? D) those changes are made in the Many protocol specification, then added to the framework, then added to the library (ManyJS or ManyRS), and then we can use them in the UI.

**Comment by tysloan** [comment]
Adding note that we discussed the order of complexity for error handling. The acceptance criteria has been adjusted accordingly - "Should present an error message ("An error occurred.") to the user (in UI) if there is an error retrieving the data.". When a backend is implemented then we will data present errors and warnings from there (ex. data is not able to update and a cached, older data point is presented).

**Comment by stanleyjones** [comment]
I think this story depends on https://github.com/liftedinit/roadmap/issues/40.

**Comment by stanleyjones** [comment]
And it's live here: http://liftedinit-talib.herokuapp.com



![Image](https://user-images.githubusercontent.com/405258/222827389-b91e58ac-2926-4cda-84f2-d10bf7d68fa8.png)
