### ISSUE TITLE
View the current network status via a UI (Talib)

### ISSUE THREAD

**Issue by tysloan** [liftedinit/roadmap#34]
Description: This is an end-to-end implementation of our block explorer, Talib. The network status should be able to be presented in the UI of Talib from the current network API. Network status is similar to a health check. This should be deployed to QA.

Story ROI
Customer Need: This block explorer story enables users to quickly view that the status of the selected network. Viewing the network status is another step to fully implemented blocked explorer for users but shows the network is live and real. 

Business Objective: Talib provides core functionality to make transactions and the Manifest blockchain network externally visible. This project has been in the works for a long time and should be completed.

**As a user, I want to view the current network status of a network so that I stay informed.**

- [x] Should be achievable via a UI (Talib).
- [x] Should be achievable via library (many-js).
- [x] Should be available from the network API (many-framework).
- [x] Should present the current network status (similar to a health check).
- [x] Should present green circle with "currently available" if the network is available and functioning properly.
- [x] Should present red circle with "currently unavailable" if the network is not available or not functioning properly.
- [x] Should present an error message to the user (in UI) if there is an error retrieving the data.
- [x] Should be deployed to QA environment. 
- [x] Should be able to be demoed as an E2E implementation.

Design:

![Image](https://user-images.githubusercontent.com/113936517/200843929-1991feef-92ba-4ba2-adfa-5b03f96cb44d.png)

[PRD](https://docs.google.com/document/d/1YZYTwH3byq6e_ZdzDiEJD9CKgRPU1qRoqgbiQI-hGIA/edit?usp=sharing)

-------------------------------
Tasks:

**Comment by stanleyjones** [comment]
Now available here: http://liftedinit-talib.herokuapp.com
