### ISSUE TITLE
Mint custom tokens via a UI

### ISSUE THREAD

**Issue by tysloan** [liftedinit/roadmap#37]
Description: This is Web2/3 developers who need to mint custom tokens on an existing network. The mint custom tokens feature will benefit users who want them for reward tokens, utility tokens, and more. This functionality should be achievable via a UI (Gwen). Many-rs work for this completed in #56 .

Story ROI
Customer Need: Tokens need to be minted for node owners.

Business Objective: Simpler way to pay node owners. Enable more development and use cases to occur on the Manifest Network. This can lead to more network usage.

**As developer, I want to mint tokens so that end-users can have and transact them.**

- [x] Should be achievable via a UI (Gwen).
- [x] Should be able to mint tokens of an existing symbol (ex. MFX) as the token owner.
- [x] Should be able to input the number of tokens that will be minted.
- [x] Should be able to input the address that the minted tokens will go to.
- [x] Should present an error message if the address does not exist.
- [x] Should increase the total supply of the minted token.
- [x] Should be able to transact minted tokens after they are created.
- [x] Should NOT be able to mint a token if the user is not a token owner.
- [x]  Should be demoed.

Notes:
- Hans will be the main customer now. 
- Future implementation could be multi-sig or DAO. 

Design: #90 

--------------------
Tasks:

**Comment by stanleyjones** [comment]
See https://github.com/liftedinit/gwen/pull/45

**Comment by stanleyjones** [comment]
**Should increase the total supply of the minted token.**

![Image](https://github.com/liftedinit/roadmap/assets/405258/110e5ef5-55c4-4709-8d2b-6e64cf230137)
