### ISSUE TITLE
Burn custom tokens via a UI

### ISSUE THREAD

**Issue by tysloan** [liftedinit/roadmap#38]
Description: This is Web2/3 developers who need to burn custom tokens on an existing network. The burn custom tokens feature will benefit users who want them for reward tokens, utility tokens, and more. This functionality should be achievable via a UI (Gwen). This story is associated with #37 . Many-rs work completed for this in #57  .

Story ROI
Business Objective: Enabling more development and use cases to occur on the Manifest Network. This can lead to more network usage.

**As a token owner, I want to burn tokens so that they are removed from my ecosystem.**

- [x] Should be achievable via a UI (Gwen).
- [x] Should be able to burn tokens of an existing symbol (ex. MFX) as a token owner
- [x] Should be able to input the number of custom tokens that will be burned.
- [x] Should NOT be able to burn more tokens than are owned.
- [x] Should be able to input the address that the tokens will be burned from.
- [x] Should present an error message if the symbol cannot be burned (fixed number of tokens) or if the address does not exist.
- [x] Should reduce the total supply of the token after burning.
- [x] Should be demoed.

Design: #90 

------------------------------------
Tasks:

**Comment by stanleyjones** [comment]
See https://github.com/liftedinit/gwen/pull/45

**Comment by stanleyjones** [comment]
**Should NOT be able to burn more tokens than are owned.**

![Image](https://github.com/liftedinit/roadmap/assets/405258/2a422bb5-e8af-4f1d-99f1-103f48644fef)

**Should present an error message if the symbol cannot be burned (fixed number of tokens) or if the address does not exist.**

![Image](https://github.com/liftedinit/roadmap/assets/405258/2dd0ead3-4fec-4cf0-917a-fcc717f0f1cf)

**Should reduce the total supply of the token after burning.**

![Image](https://github.com/liftedinit/roadmap/assets/405258/810b6703-b2d0-4ead-865d-56d74ac4ad49)
