### ISSUE TITLE
[tracking] Web3Auth integration with frontends

### ISSUE THREAD

**Issue by hansl** [liftedinit/roadmap#4]
TODO: Discuss this with Tommy.

**Comment by hansl** [comment]
# Status

Blocking: Need some discussion between eng and product, about what it means to integrate accounts and web3auth.

**Comment by tt0mmy** [comment]
PRD: https://coda.io/d/Product-Request-Document-Sign-On_dW0YgLYZSh0/PRD-Sign-On_sujsr#_luA1L

**Comment by hansl** [comment]
This is blocked currently as Tommy is working to help on the block explorer.

**Comment by hansl** [comment]
Product team still working on streamlining the sign on flow. Still blocked.

Target for deliverable; end of week to get a proper scope and acceptance criteria.

**Comment by hansl** [comment]
Unblocked by the product team. Tommy to get started soon.

**Comment by fmorency** [comment]
@tantommy is almost done with this task. Will be demoed in all-hands Wed.
