### ISSUE TITLE
View the Blocks List via a UI (Talib)

### ISSUE THREAD

**Issue by tysloan** [liftedinit/roadmap#41]
Description: This is an end-to-end implementation of our block explorer, Talib. The Blocks List data should be presented in the Dashboard UI of Talib.  QA is the target environment.

Story ROI
Customer Need: This block explorer story enables users to transparently view the latest blocks  for a network.

Business Objective: Talib provides core functionality to make transactions and the Manifest blockchain network externally visible. This project has been in the works for a long time and should be completed.

As a user, I want to view the Blocks List of a network so that I stay informed.

- [x] Should be achievable via a UI (Talib).
- [x] Should present the Block Number.
- [x] Should present the Timestamp.
- [x] Should present the Number of Txs in the block.
- [x] Should present an error message to the user (in UI) if there is an error retrieving the data.
- [x] Should be able to be demoed as an E2E implementation.

Design: Adapt the below design to match our branding and styling. Will look at Cosmos mintscan.

Mintscan:
![Image](https://user-images.githubusercontent.com/113936517/220705914-c417634d-0d3b-430e-9a24-029d0b45ebc8.png)

![Image](https://user-images.githubusercontent.com/113936517/208761759-e6193036-443f-469f-a4e5-11619ab9782a.png)

WhitePrompt design for reference:
![Image](https://user-images.githubusercontent.com/113936517/204389126-e9cc9906-96e5-4189-bde0-9eb9324e5f59.png)

[PRD](https://docs.google.com/document/d/1YZYTwH3byq6e_ZdzDiEJD9CKgRPU1qRoqgbiQI-hGIA/edit?usp=sharing)

------------------------
Tasks:

**Comment by stanleyjones** [comment]
Now available here: http://liftedinit-talib.herokuapp.com
