### ISSUE TITLE
Stand up Talib on PaaS

### ISSUE THREAD

**Issue by tysloan** [liftedinit/roadmap#44]
Description: This story is to stand up Talib on a Platform as a Service so that we can build in deploy more quickly. Talib and our frontend apps are not decentralized features and do not necessarily need to be stood up on decentralized infrastructure. 

Story ROI
Business Objective: Enabling quicker deployment of Talib  and other frontend apps so that we can continue engineering stories related to them. 

**As an engineer, I want to stand up Talib on a Platform as a Service so that I can quickly deploy.** 

- [x] Should choose a Platform as a Service based on performance, reliability, and cost efficiency.
- [x] Should standup current Talib app in a dev environment on the chosen PaaS.
- [x] Should include the current completed stories for Talib.
- [x] Should be able to be demoed. 

------------------------
Tasks:

**Comment by stanleyjones** [comment]
Live here: http://liftedinit-talib.herokuapp.com

**Comment by stanleyjones** [comment]
Accepted as done via Slack.
