### ISSUE TITLE
Upgrade to latest framework RC in QA

### ISSUE THREAD

**Issue by tysloan** [liftedinit/roadmap#46]
Description: We have to upgrade to the latest RC from RC7 as well. This is necessary to increase our security and stability. Related Tendermint work is in #6 .

Story ROI
Business Objective: By moving to the latest RC we will be able to increase network security.

As an engineer, I want to upgrade to the latest framework RC so that we increase security.

- [ ] ~Should clone production network to QA environment?~ Removed during estimation.
- [x] Should run upgrade to latest RC in QA environment
- [x] Should thoroughly test RC upgrade on nodes.
- [x] Should document procedure plan to run prod upgrade to latest RC.

------------------
Tasks:

**Comment by fmorency** [comment]
We will have another RC ready by then. RC9 is already a few months old.

**Comment by stanleyjones** [comment]
Target environment is QA. A separate story will be created for prod migration.

**Comment by stanleyjones** [comment]
Re-estimated but keeping at an 8 to account for "thoroughly test RC upgrade" criterium.

**Comment by stanleyjones** [comment]
Can you link the docs here @jgryffindor ?

Demoed as done!

**Comment by jgryffindor** [comment]
Docs for RC10 upgrade process and next steps:
https://coda.io/d/TechOps-Execution-Planning_djT-HzCHnnp/RC10-Upgrade_sukyj#_lujUX  
https://coda.io/d/Release-Upgrade-Notes_d1X-W_srznR/RC7-to-RC10-migration-path_suIkO

**Comment by fmorency** [comment]
Test document: https://coda.io/d/_d1X-W_srznR/RC7-to-RC10-migration-path_suIkO
Hybrid network test repo: https://github.com/fmorency/a-vs-b
