### ISSUE TITLE
Upgrade to RC 14 in prod

### ISSUE THREAD

**Issue by tysloan** [liftedinit/roadmap#47]
Description: Upgrade to the latest RC from RC11. This is necessary to increase our security and stability. Related to #46 .

Story ROI
Business Objective: By moving to the latest RC we will be able to active features for Token, Data and Memo migrations and successfully mint/burn tokens.

**As an engineer, I want to upgrade to the latest framework RC so that we can mint/burn tokens.**

- [x] Should follow procedure for production and obtain team approval, schedule prod upgrade
- [x] Should implement a backup pipeline from QA role development
- [x] Should be thoroughly test by team in QA.
- [x] Should run prod upgrade to latest RC14 on a Canary node
- [ ] Should have a backup beforethe migration executes, approximately 4 hours prior is a good target with current tooling.
- [ ] Should run prod upgrade to latest RC14 on remaining nodes
- [ ] Should thoroughly test RC upgrade on nodes
- [ ] Should create an outline document for what is included in the latest RC that can be shared publicly

------------------------
Tasks:

**Comment by fmorency** [comment]
[RC11](https://github.com/liftedinit/many-framework/releases/tag/0.1.0-alpha-rc11 ) was released and is ready to be tested.

**Comment by rfisch** [comment]
Will be upgraded to RC14 for token mint/burn features.
