### ISSUE TITLE
Talib Header

### ISSUE THREAD

**Issue by tysloan** [liftedinit/roadmap#49]
Description: This story is for the Header section of Talib. A Talib logo should be in the top left screen and the right side should have a Network drop down (similar to Alberto). A user should be able to select from available networks (Manifest and END). Should be able to be accomplished with the work completed in #40 . Hardcoded for information we are scanning for. 

Story ROI
Customer Need: Customers will use Talib to view metrics of different networks so they need a place to choose which one they are interested in.

Business Objective: Better user experience. Talib provides core functionality to make transactions and the network data externally visible. This project has been in the works for a long time and should be completed.

**As a user, I want to select a specific Ledger in Talib so that I can view information about it.**

- [x] Should be achievable via a UI (Talib).
- [x] Should present the Talib logo in the top left of the header.
- [x] Should present the Network drop down in the top right of the header. 
- [x] Should present the Manifest Ledger as the default option in the drop down.
- [x] Should be deployed to QA environment.
- [x] Should be demoed.

Alberto screenshots for reference: There will not be an option to "Add Network".

![Image](https://user-images.githubusercontent.com/113936517/208761269-53af3d08-2bdc-4291-b36f-04d8864210c5.png)

[PRD](https://docs.google.com/document/d/1YZYTwH3byq6e_ZdzDiEJD9CKgRPU1qRoqgbiQI-hGIA/edit?usp=sharing)
-------------------
Tasks:

**Comment by stanleyjones** [comment]
Demoed and accepted!
