### ISSUE TITLE
View Transactions List in Talib

### ISSUE THREAD

**Issue by tysloan** [liftedinit/roadmap#50]
Description: This is the end-to-end implementation of transactions that occur on a network displayed in Talib on the main Dashboard screen. The design and functionality should be the same regardless of what Network is selected.

Story ROI
Customer Need: This block explorer story enables users to transparently view the latest transactions for a network. 

Business Objective: Talib provides core functionality to make transactions and the Manifest blockchain network externally visible. This project has been in the works for a long time and should be completed.

**As a user, I want to view the the latest transactions of a network so that I stay informed.**

FE:
- [x] Should be achievable via a UI (Talib).
- [x] Should present the latest transactions list in the Dashboard of Talib.
- [x] Should present the five latest transactions with a "View all transactions" button at the bottom.
- [x] Should present the same information that is in the below design without the "Tx" circle. 
- Tx Hash
- Timestamp
- From address
- To address (optional if exists)
- Type (method)
- Token symbol (optional if exists)
- Token amount (optional if exists)
- [x] Should present an error message ("An error occurred.") to the user (in UI) if there is an error retrieving the data.
- [x] Should be demoed as an E2E implementation.

BE:

- [x] API should provide the following information:
  - [x] TX Hash
  - [x] Timestamp
  - [x] From address
  - [x] To address
  - [x] Method
  - [x] For `ledger.send`:
    - [x] Token
    - [x] Amount

Design: Adapt the below design to match our branding and styling.

Mintscan: 
![Image](https://user-images.githubusercontent.com/113936517/220705722-0998aa93-03e6-4b85-8f3e-c8e9aca66e06.png)

![Image](https://user-images.githubusercontent.com/113936517/208761718-fe99ee3f-ce08-4960-935d-c8e134d1a90b.png)

WhitePrompt design for reference:
![Image](https://user-images.githubusercontent.com/113936517/208709540-754ce7e3-48ce-4ba0-93b6-00571e9b4b21.png)

[PRD](https://docs.google.com/document/d/1YZYTwH3byq6e_ZdzDiEJD9CKgRPU1qRoqgbiQI-hGIA/edit?usp=sharing)
-----------
Tasks:

**Comment by stanleyjones** [comment]
Now live here: http://liftedinit-talib.herokuapp.com

**Comment by stanleyjones** [comment]
Demoed and accepted!
