### ISSUE TITLE
View Transaction Details page in Talib

### ISSUE THREAD

**Issue by tysloan** [liftedinit/roadmap#51]
Description: This is the end-to-end implementation of Transaction Details that occur on a network displayed in Talib when a specific transaction is selected by a user. This should navigate the user to a new screen with the details. The design and functionality should be the same regardless of what Network is selected.

Story ROI
Customer Need: This block explorer story enables users to transparently view  transaction details for a network. Viewing transaction details ensures users that their transaction went through properly and can be audited.

Business Objective: Talib provides core functionality to make transactions and the Manifest blockchain network externally visible.  This project has been in the works for a long time and should be completed.

**As a user, I want to view the the details of a specific transaction so that I stay informed.**

- [x] Should be achievable via a UI (Talib).
- [x] Should present transaction details on its own page in Talib.
- [x] Should present the following details for each transaction:
- Tx Hash
- Timestamp
- Status (Success or Fail)
- From address
- To address (optional if exists)
- Token symbol (optional if exists)
- Token amount (optional if exists)
- Block Number (Height)
- [x] Should present an error message ("An error occurred.") to the user (in UI) if there is an error retrieving the data.
- [x] Should be demoed as an E2E implementation.

Design: Adapt the below design to match our branding and styling.

![Image](https://user-images.githubusercontent.com/113936517/209221511-e91be2a2-13f7-40c8-8721-6f1d3915ec4f.png)

WhitePrompt design for reference:
![Image](https://user-images.githubusercontent.com/113936517/208712507-45f21c0d-a021-4c5a-a4aa-6cf9fa3611d5.png)

[PRD](https://docs.google.com/document/d/1YZYTwH3byq6e_ZdzDiEJD9CKgRPU1qRoqgbiQI-hGIA/edit?usp=sharing)
-------------------
Tasks:

**Comment by stanleyjones** [comment]
Demoed and accepted!
