### ISSUE TITLE
View Block Details page in Talib

### ISSUE THREAD

**Issue by tysloan** [liftedinit/roadmap#52]
Description: This is the end-to-end implementation of Block Details for Talib. When a specific block is selected by a user on the Dashboard, they should be navigated to a new screen with that block's details. The design and functionality should be the same regardless of what Network is selected.

Story ROI
Customer Need: This block explorer story enables users to transparently view the details for a specific block on a network.

Business Objective: Talib provides core functionality to make transactions and the Manifest blockchain network activity externally visible. This project has been in the works for a long time and should be completed.

**As a user, I want to view the the details of a specific block so that I stay informed.**

- [x] Should be achievable via a UI (Talib).
- [x] Should present block details on its own page in Talib.
- [x] Should present the follow fields for block details:
-  Block Height
- Timestamp
- Number of Txs in the block.
- Table with transactions that are in the block
         - Tx Hash
         - Timestamp
         - From address
         - To address (optional if exists)
         - Type (method)
         - Token symbol (optional if exists)
         - Token amount (optional if exists)
- [x] Should present an error message ("An error occurred.") to the user (in UI) if there is an error retrieving the data.
- [x] Should be demoed as an E2E implementation.

Design: Adapt the below designs to match our branding and styling.

![Image](https://user-images.githubusercontent.com/113936517/208773060-f68567d8-1968-4eb7-b519-b6542c7153c2.png)

WhitePrompt design for reference:
![Image](https://user-images.githubusercontent.com/113936517/208715529-af66931a-0a60-436f-99c9-ee957e740cdb.png)

Mintscan for Cosmos example:

![Image](https://user-images.githubusercontent.com/113936517/212173592-e0faab3e-5a48-444a-8cc9-3c21f9a2903d.png)
![Image](https://user-images.githubusercontent.com/113936517/212173637-256c1db7-faa2-400e-b84a-6be3ec3394a3.png)

Notes:
- Could consider adding block hash in a future version.

[PRD](https://docs.google.com/document/d/1YZYTwH3byq6e_ZdzDiEJD9CKgRPU1qRoqgbiQI-hGIA/edit?usp=sharing)
-----------------
Tasks:

**Comment by stanleyjones** [comment]
Now live here: http://liftedinit-talib.herokuapp.com/#/blocks/059e5553f34473cbbddd2aeeb9c1a8207e91b561ff50b2939103e24247841907

**Comment by stanleyjones** [comment]
Demoed and accepted!
