### ISSUE TITLE
View Address Details in Talib

### ISSUE THREAD

**Issue by tysloan** [liftedinit/roadmap#53]
Description: This is the end-to-end implementation of Address Details for Talib. When a specific address is selected by a user on the Dashboard or on a Transactions screen, they should be navigated to a new screen with that address's details. The design and functionality should be the same regardless of what Network is selected.

Story ROI
Customer Need: This block explorer story enables users to transparently view the details for a specific address on a network.

Business Objective: Talib provides core functionality to make transactions and the Manifest blockchain network activity externally visible.  This project has been in the works for a long time and should be completed.

**As a user, I want to view the the details of a specific address so that I stay informed.**

- [x] Should be achievable via a UI (Talib).
- [x] Should present address details on its own page in Talib.
- [x] Should present the follow details for the address:
- Address
- Table with transactions for the address
        - Tx Hash
        - Timestamp
        - Status (Success or Fail)
        - From address
        - To address (optional if exists)
        - Token symbol (optional if exists)
        - Token amount (optional if exists)
        - Block Number (Height)
- [x] Should present an error message ("An error occurred.") to the user (in UI) if there is an error retrieving the data.
- [x] Should be demoed as an E2E implementation.

Notes:
- Could implement events now (would be easier) and long-term work on proper transactions. 
- For address appearing anywhere. 
- Balance needs more design and exploration. 
-  Could query the backend for the balance similar to Alberto.
- May be difficult with multi-sig. Would have to check, did this execute? 
- Removing balance from this story to be separate with requirements for items such as mint/burn of tokens.

Design: Adapt the below designs to match our branding and styling.

Mintscan example:
![Image](https://user-images.githubusercontent.com/113936517/222172744-83083cb8-207e-4d3b-b0d0-d6cbb9c81b20.png)
![Image](https://user-images.githubusercontent.com/113936517/222172818-ea5fa86b-9b35-4e51-a5b6-1ced992585fc.png)
![Image](https://user-images.githubusercontent.com/113936517/222172902-dcc08d80-db7c-4785-99a9-ab265eb5f77b.png)

Polyscan:
![Image](https://user-images.githubusercontent.com/113936517/208773461-a12af564-3c59-4806-bd74-0fc64b1a46fd.png)

WhitePrompt design for reference:
![Image](https://user-images.githubusercontent.com/113936517/208717714-7f38ad06-584c-48cc-be6a-90f9ebfb979c.png)

[PRD](https://docs.google.com/document/d/1YZYTwH3byq6e_ZdzDiEJD9CKgRPU1qRoqgbiQI-hGIA/edit?usp=sharing)
-----------
Tasks:

**Comment by stanleyjones** [comment]
See it live here: http://liftedinit-talib.herokuapp.com/#/addresses/mahax7zghro7xzfgc6md6r2rvpieghttpf6nrmbw3omfrkzixo

**Comment by stanleyjones** [comment]
Demoed!
