### ISSUE TITLE
Search in Talib

### ISSUE THREAD

**Issue by tysloan** [liftedinit/roadmap#54]
Description: This is the end-to-end implementation of Search within a network that will be displayed in the sticky header of Talib. The design and functionality should be the same regardless of what Network is selected. The types of things users can search for include: Address, Txn Hash, or Block. For a specific Address, Txn Hash, or Block height, the user should be navigated to a new page (same tab) with the details of that specific item (ex. Address details -> #53 ). 

Story ROI
Customer Need: This block explorer story enables users to search and quickly find information and data for a network. 

Business Objective: Talib provides core functionality to make transactions and the Manifest blockchain network externally visible.  This project has been in the works for a long time and should be completed.

**As a user, I want to search for specific data so that I save time.**
 
- [x] Should be achievable via a UI (Talib).
- [x] Should be able to search for an Address, Txn Hash, or Block height.
- [x] Should navigate user directly to a successful search results in Talib.
- [x] Should present an error message ("Not found.") to the user (in UI) if there is an error retrieving the data.
- [x] Should be demoed as an E2E implementation.

Notes:
- Can be achieved from the frontend. 
- Will use block height for search not hash. 

Design: Adapt the below designs to match our branding and styling. 

Internal design:
Instead of "Search..." the pretext in the search bar should say "Search by Address, Txn Hash, Block"

![Image](https://user-images.githubusercontent.com/113936517/208719324-6255d652-d12b-4b3c-9a4a-8c3fc10dbf25.png)

Mintscan for Cosmos example:
![Image](https://user-images.githubusercontent.com/113936517/208773652-ee364a78-a52b-48c5-bc01-98e7d4733a27.png)

Polyscan example:
![Image](https://user-images.githubusercontent.com/113936517/208773693-1c953c08-5ba7-4d02-a1f6-1337f964ad8e.png)

[PRD](https://docs.google.com/document/d/1YZYTwH3byq6e_ZdzDiEJD9CKgRPU1qRoqgbiQI-hGIA/edit?usp=sharing)
---------------------
Tasks:

**Comment by stanleyjones** [comment]
Need to get block by height instead of hash to finish this issue.

**Comment by stanleyjones** [comment]
Now working in prod: https://talib.liftedinit.app/
 
Search for "852929".
