### ISSUE TITLE
View the number of transactions via a UI (Talib)

### ISSUE THREAD

**Issue by tysloan** [liftedinit/roadmap#55]
Description: This is an end-to-end implementation of our block explorer, Talib. The total number of transactions for a network should be presented in the main dashboard. QA is the target environment.

Transaction definition is located in the many-spec.

Story ROI
Customer Need: This block explorer story enables users to transparently view the number of transactions of a selected Ledger. 

Business Objective: Talib provides core functionality to make transactions and the Manifest blockchain network externally visible. This project has been in the works for a long time and should be completed.

**As a user, I want to view the total number of transactions for a network so that I stay informed**

- [x] Should be achievable via a UI (Talib).
- [x] Should be achievable via library (many-js).
- [x] Should be available from the network API (many-framework).
- [x] Should present the total number of transactions for that ledger.
- [x] Should present an error message ("An error occurred.") to the user (in UI) if there is an error retrieving the data.
- [x]  Should be deployed to QA environment.
- [x] Should be able to be demoed as an E2E implementation.

Design: Adapt the below design to match our branding and styling.

![Image](https://user-images.githubusercontent.com/113936517/208968013-fd8bfd3e-b2a7-4e7d-82ff-e1e9590004d9.png)

[PRD](https://docs.google.com/document/d/1YZYTwH3byq6e_ZdzDiEJD9CKgRPU1qRoqgbiQI-hGIA/edit?usp=sharing)
--------------
Tasks:

**Comment by tysloan** [comment]
Team questions: 
- Should prod Talib be on Heroku or on our own Network?
- What is specifically included for transactions?

**Comment by stanleyjones** [comment]
Live here: http://liftedinit-talib.herokuapp.com

![Image](https://user-images.githubusercontent.com/405258/222827535-2164dc94-dd05-42fb-8576-db4977d46e5c.png)
