### ISSUE TITLE
Mint tokens

### ISSUE THREAD

**Issue by tysloan** [liftedinit/roadmap#56]
Description: This story is the many-rs implementation for minting tokens. This includes minting more tokens of an existing symbol (as the "owner"). This has been moved up in priority so that more MFX can be minted to compensate node providers. Minting as a full feature will also benefit Liftoff Program members and Web2/3 developers who need to mint custom tokens on an existing network. This story is to send the feature to production.

Story ROI
Customer Need: MFX tokens need to be minted for node owners. Also, Liftoff Program team has requested a way to mint a custom token on an existing network to replace their in-app currency with a blockchain-based token.

Business Objective: Compensate node owners. Enable more development and use cases to occur on the Manifest Network. This can lead to more network usage.

**As a developer, I want to mint tokens so that end-users can transact them.**

- [x] Should be achievable via many-rs.
- [x] Should be able to mint more tokens of an existing symbol (ex. MFX) as the address that originally generated them.
- [ ] ~Should be able to mint a new symbol (3-5 letter limit) - can remove to limit scope.~ Removed during estimation
- [x] Should present an error message if ~the symbol is already taken on the network and~ it is not the address that originally generated the symbol that is attempting to mint.
- [x] Should be able to input the number of tokens that will be minted.
- [x] Should be minted to the address that is creating them.
- [x] Should be able to transact minted tokens after they are generated.
- [x] Should be deployed to QA (but see #47)
- [x] Should be able to be demoed.

--------------------
Tasks:

**Comment by stanleyjones** [comment]
What financial and/or legal implications are there around minting tokens into the treasury and then transferring vs issuing from the existing treasury balance?

**Comment by fmorency** [comment]
@tysloan `Should present an error message if the symbol is already taken on the network` that doesn't make sense.

**Comment by tysloan** [comment]
> @tysloan `Should present an error message if the symbol is already taken on the network` that doesn't make sense.

Agreed, that should have been removed in estimation with the item above it. I crossed that part out.

**Comment by rfisch** [comment]
waiting for team testing via CLI.
