### ISSUE TITLE
Burn tokens

### ISSUE THREAD

**Issue by tysloan** [liftedinit/roadmap#57]
Description: This story is the many-rs implementation for burning tokens. This story includes burning tokens of an existing symbol (as the "owner"). This has been moved up in priority so that more MFX can be minted to compensate node providers. Burning will be important for tokeneconomic purposes and the minting/burning as a full feature will also benefit Liftoff Program members and Web2/3 developers. This story is to send the feature to production.

Story ROI
Customer Need: MFX tokens need to be minted for node owners. There will soon be a need to burn them as well. Also, Liftoff Program team has requested a way to mint/burn a custom token on an existing network to replace their in-app currency with a blockchain-based token.

Business Objective: Enable functionality that supports our tokeneconomics. Enable more development and use cases to occur on the Manifest Network. This can lead to more network usage.

**As developer, I want to burn tokens so that they are removed from my economy.**

- [x] Should be achievable via many-rs.
- [x] Should be able to burn tokens of an existing symbol (ex. MFX) as the address that owns them
- [x] Should present an error message if the symbol cannot be burned (fixed number of tokens) or if it is not an owner of the symbol that is attempting to be burned.
- [x] Should be able to input the number of tokens that will be burned.
- [x] Should not be able to burn more tokens than are owned
- [x] Should reduce the total supply of the burnt token
- [x] Should be deployed to QA (but see #47)
- [x] Should be able to be demoed.

------------------
Tasks:

**Comment by rfisch** [comment]
waiting for team testing via CLI.
