### ISSUE TITLE
Mint and burn tokens in prod

### ISSUE THREAD

**Issue by tysloan** [liftedinit/roadmap#59]
Description: This story is to propagate the many-rs mint #56 and burn #57  tokens features to production.

Story ROI
Customer Need: MFX tokens need to be minted for node owners. There will soon be a need to burn them as well. Also, Liftoff Program team has requested a way to mint a custom token on an existing network to replace their in-app currency with a blockchain-based token.

Business Objective: Pay node owners. Enable functionality that supports our token economics. Enable more development and use cases to occur on the Manifest Network. This can lead to more network usage.

**As a developer, I want to mint and burn tokens so that my token economy is supported.**

- [x] Should propagate mint feature to production #56 
- [x] Should propagate burn feature to production #57 
- [x] Should thoroughly test mint and burn in production
- [x] Should be able to demo in prod

-----------
Tasks:

**Comment by tysloan** [comment]
Q: Any legal (ex. taxable event) implications for minting tokens?

**Comment by fmorency** [comment]
@hansl tested this feature in production.
