### ISSUE TITLE
Automate the CI for Talib

### ISSUE THREAD

**Issue by tysloan** [liftedinit/roadmap#61]
Description: This story is related to #44 and is the part that automates the CI for the push to stage/QA on the selected PaaS. 

Story ROI
Business Objective: Enabling quicker deployment of Talib and other frontend apps so that we can continue engineering stories related to them.

**As an engineer, I was to automate my pushes to stage for Talib so that I save time.**

- [x] Should implement CI automation for the push to stage/QA for Talib.
- [x] Should be able to be demoed.

**Comment by stanleyjones** [comment]
Live here: http://liftedinit-talib.herokuapp.com

Currently pulling from this branch: https://github.com/liftedinit/talib/tree/heroku

CircleCI pipeline: https://app.circleci.com/pipelines/github/liftedinit/talib

Heroku dashboard: https://dashboard.heroku.com/apps/liftedinit-talib

**Comment by stanleyjones** [comment]
Accepted as done via Slack.
