### ISSUE TITLE
Test data, memo and token migrations in QA

### ISSUE THREAD

**Issue by stanleyjones** [liftedinit/roadmap#63]
Description: Test database migration in QA

Story ROI:
1. Be compliant with the current specification, e.g., memo
2. Provide new features to customers, e.g., token creation/mint/burn

As a developer, I want to
- [x] Apply database migration at a given (future) block height on all nodes in QA
- [x] Use new features/endpoints/data provided by the migrations
- [x] Develop backup tasks for ansible roles to be used in QA/Prod migrations to push backups from OMC nodes in the event of a failed migration.
- [x] Configure backup pipeline for DR recovery events and test a DR event.

**Comment by fmorency** [comment]
Works in dev.
