### ISSUE TITLE
Cron job for Talib

### ISSUE THREAD

**Issue by tysloan** [liftedinit/roadmap#79]
Description: A cron needs to be created for Talib to function and fetch things such as latest block height.

As a user, I want Talib to be updated so that I can view the latest information about a network. 

- [x] Should create cron for Talib app to show the latest block height at that time.
- [x] Should update every [X].
- [x] Should be deployed to QA.
- [x] Should be able to be demoed.

**Comment by fmorency** [comment]
On track to be demoed on Heroku next week.
