### ISSUE TITLE
Test environment for Alpha Cohort members

### ISSUE THREAD

**Issue by tysloan** [liftedinit/roadmap#81]
Description: Liftoff Program members need an environment to test new features moved to QA/Staging such Generate custom token pool or KVStore. We will need to create a test environment or network for them to do so and provide feedback. Will require a custom build so that anyone can create tokens. We will be able to monitor activity on the test network. Having metrics on network usage can be useful for future cost/price calculations. 

ROI: Receive feedback on existing features, keep Cohort members engaged, and inspire them to build on the Manifest Network.

**As TLI, I want to Liftoff Program members to test features so that we have an external feedback loop.** 

- [x] Should be a test network.
- [x] Should contain the generate custom token pool and kvstore features.
- [x] Should reset every [X].
- [x] Should be accessible by Liftoff Program members.
- [x] Should have a limit or cap for amount of pings or network usage.

Notes:
- Use cloud for this but schedule time for virtualizing our current process. 
- Need to discuss with Eric what the strategy be for this. The issue/goal should be re-addressed after that conversation. 
- Is a dev tier (internal).

**Comment by tysloan** [comment]
@fmorency will sync with @jgryffindor on the stack for this.

**Comment by stanleyjones** [comment]
Demoed and accepted!
