### ISSUE TITLE
Talib Production Deployment

### ISSUE THREAD

**Issue by tysloan** [liftedinit/roadmap#82]
Description: Will need to deploy Talib for the Manifest network.

- [x] Should should be caught up to current state.
- [x] Should have its own domain (talib.liftedinit.app)
- [x] Should be demoed 

Notes:
- Can use Heroku. 
- Can consider having a QA as well in the future.

**Comment by stanleyjones** [comment]
I've done up to this step in Heroku: https://devcenter.heroku.com/articles/custom-domains#configuring-dns-for-subdomains

Someone needs to add a `CNAME` for `talib` to point to `horizontal-walrus-vjx3zzzuiilgk350ufs9vdbf.herokudns.com` in our `liftedinit.app` DNS record and it should start working.

**Comment by stanleyjones** [comment]
Now live at https://talib.liftedinit.app.

Just waiting for block height to catch up.
