### ISSUE TITLE
Mint/Burn Tokens Gwen Design

### ISSUE THREAD

**Issue by tysloan** [liftedinit/roadmap#90]
Description: Design ticket for #37 and #38. 

- [ ] Should update above tickets with UI design.

**Comment by stanleyjones** [comment]
**LIST VIEW**

![Image](https://github.com/liftedinit/roadmap/assets/405258/a857fc70-e73e-4257-b097-ab81314e84f7)

Added an icon for edit/update, which is allowed b the spec but not in scope for this story.

**Comment by stanleyjones** [comment]
**MINT MODAL**

![Image](https://github.com/liftedinit/roadmap/assets/405258/107007a8-8bb5-4b6d-b77e-c48b455c5c43)

**BURN MODAL**

![Image](https://github.com/liftedinit/roadmap/assets/405258/246cc135-859d-4678-b348-dd6991e25134)

Not exactly Rembrandt but they should be a good starting point.

**Comment by stanleyjones** [comment]
Approved by @tysloan over Zoom.
