### ISSUE TITLE
View requests and responses in Talib

### ISSUE THREAD

**Issue by tysloan** [liftedinit/roadmap#93]
Description: We have the information to display the request and response information for transaction details in Talib similar to Kaylee. Previous trouble was had in getting it to wrap for proper display. This is for QA environment. 

As a user I want to view the requests and responses in Talib so that I stay informed. 

- [x] Should display request and response information for transactions in Talib.
- [x] Should be demoed. 

Example from Mintscan:

![Image](https://user-images.githubusercontent.com/113936517/228562408-234ccd55-de92-4dea-8d7a-105288486067.png)

**Comment by stanleyjones** [comment]
Request and responses as raw CBOR-encoded hex are now available:

http://liftedinit-talib.herokuapp.com/#/transactions/5b54cf1118925baa8a3b8addabf8d577400afebfeb61eb6de2067848f66fd210

**Comment by stanleyjones** [comment]
Demoed!
