### ISSUE TITLE
Support more methods for Talib

### ISSUE THREAD

**Issue by tysloan** [liftedinit/roadmap#96]
Description: The backend enables us to support more methods for Talib such as mint/burn and multi-sig transactions. We can work to parse and include these additional types of events in the frontend. This work will also be useful for the Dashboard of Gwen.

- [x] Should support mint/burn tokens.
- [x] Should support multi-sig transactions.
- [x] Should be demoed.

Notes:
Currently used methods:
- [x]    24 │ "account.addRoles": "Add",
- [x]    25 │ "account.create": "Create",
- [x]    26 │ "account.multisigApprove": "Approve",
- [x]    27 │ "account.multisigRevoke": "Revoke",
- [x]    28 │ "account.multisigSetDefaults": "Set",
- [x]    29 │ "account.multisigSubmitTransaction": "Submit",
- [x]    30 │ "account.multisigWithdraw": "Withdraw",
- [x]    31 │ "account.removeRoles": "Remove",
- [x]    32 │ "idstore.store": "Register",
- [x]    33 │ "ledger.send": "Send",
- [x]    34 │ "tokens.burn": "Burn",
- [x]    35 │ "tokens.mint": "Mint",

**Comment by tysloan** [comment]
@hansl would you like these broken into separate tickets for each?

**Comment by hansl** [comment]
You're missing a few, but I've got you :) Using the spec for source of truth.
